language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.4
env:
  global:
    - secure: fTRLueIhgf6WKpZN7Mfkr/ARCVdGr9wRD7UOoDSOjrlGp41X2x0MnBzrzgl7PH8VwwVO8Gf5hA4Ddotl6R2fOiZROtmPifIp28BQiJlgNIVuAb9Ua8PeSNt1GZQPDDMdTL/HCUoIWg5FQbHtjlGUpV04pJeQhjbdTZIThQFFtvc=
before_install:
  - gem update --system
  - gem update --remote bundler
before_script:
  - git config --global user.name "$(git --no-pager show --no-patch --format='%an')"
  - git config --global user.email "$(git --no-pager show --no-patch --format='%ae')"
script:
  - git clone -b master --depth 1 --quiet "https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" _site
  - rm -r _site/*
  - bundle exec rake spec
after_success:
  - cd _site
  - git add -A
  - git commit -m "Updated to $(git rev-parse --short $TRAVIS_COMMIT) at $(date -u +'%Y-%m-%d %H:%M:%S %Z')"
  - git push "https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" master --quiet
branches:
  only:
    - source
